/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rbcsoja;

import java.awt.AWTKeyStroke;
import javax.swing.JComboBox;

/**
 *
 * @author mayla
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DamagedArea = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cankerLesion = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        date = new javax.swing.JComboBox<>();
        externalDecay = new javax.swing.JComboBox<>();
        CropHist = new javax.swing.JComboBox<>();
        fruitSpot = new javax.swing.JComboBox<>();
        fruitingBodies = new javax.swing.JComboBox<>();
        fruitingPods = new javax.swing.JComboBox<>();
        germination = new javax.swing.JComboBox<>();
        hail = new javax.swing.JComboBox<>();
        intDiscolor = new javax.swing.JComboBox<>();
        leafMalf = new javax.swing.JComboBox<>();
        leafMild = new javax.swing.JComboBox<>();
        leafspotMargin = new javax.swing.JComboBox<>();
        leaves = new javax.swing.JComboBox<>();
        lodging = new javax.swing.JComboBox<>();
        moldGrowth = new javax.swing.JComboBox<>();
        mycellium = new javax.swing.JComboBox<>();
        plantStand = new javax.swing.JComboBox<>();
        root = new javax.swing.JComboBox<>();
        sclerotia = new javax.swing.JComboBox<>();
        seeds = new javax.swing.JComboBox<>();
        seedDiscolor = new javax.swing.JComboBox<>();
        stemCanker = new javax.swing.JComboBox<>();
        temps = new javax.swing.JComboBox<>();
        seedSize = new javax.swing.JComboBox<>();
        leafShread = new javax.swing.JComboBox<>();
        shriveling = new javax.swing.JComboBox<>();
        leafspotSize = new javax.swing.JComboBox<>();
        stem = new javax.swing.JComboBox<>();
        seetTmt = new javax.swing.JComboBox<>();
        precip = new javax.swing.JComboBox<>();
        severity = new javax.swing.JComboBox<>();
        calcularSimilariedade = new javax.swing.JButton();
        similaridadeMinima = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        leafspotHalo = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        plantGrowth = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Damaged Area");

        jLabel2.setText("Canker Lesion ");

        jLabel3.setText("Crop Hist");

        jLabel4.setText("External Decay");

        jLabel5.setText("Fruit Spot");

        DamagedArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "low-area", "upper-area", "whole-field", "scattered", "unknown" }));
        DamagedArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DamagedAreaActionPerformed(evt);
            }
        });

        jLabel6.setText("Fruiting Bodies");

        jLabel7.setText("Fruit Pods");

        jLabel8.setText("Germination");

        jLabel9.setText("Hail");

        jLabel10.setText("Int Discolor");

        jLabel11.setText("Leaf Malf");

        jLabel12.setText("Leaf Mild");

        jLabel13.setText("Leaf Shread");

        jLabel14.setText("Leafspot Size");

        jLabel15.setText("Leafspot Margin");

        jLabel16.setText("Leaves");

        jLabel17.setText("Lodging");

        jLabel18.setText("Mold Growth");

        jLabel19.setText("Mycelium");

        jLabel20.setText("Plant Stand");

        jLabel21.setText("Precip");

        jLabel22.setText("Roots");

        jLabel23.setText("Sclerotia");

        jLabel24.setText("Seed");

        jLabel25.setText("Seed Discolor");

        jLabel26.setText("Seed Size");

        jLabel27.setText("Seed Tmt");

        jLabel28.setText("Severity");

        jLabel29.setText("Date");

        jLabel30.setText("Shriveling");

        jLabel31.setText("Stem");

        jLabel32.setText("Stem Canker");

        jLabel33.setText("Temp");

        cankerLesion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brown", "Tan", "DNA", "Dk-brown-blk", "Unknown" }));
        cankerLesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cankerLesionActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("TeX Gyre Bonum", 3, 18)); // NOI18N
        jLabel34.setText("Sistema de Diagnóstico de Doenças de Soja");

        jLabel35.setFont(new java.awt.Font("Bitstream Charter", 2, 18)); // NOI18N
        jLabel35.setText("Escolha as Características referentes ao estado da soja");

        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", "Unknown" }));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        externalDecay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "firm-and-dry", "absent", "Desconhecido", "watery" }));
        externalDecay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externalDecayActionPerformed(evt);
            }
        });

        CropHist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "same-1st-yr", "same-lst-two-yrs", "diff-1st-year", "same-lst-sev-yrs", "unknown" }));
        CropHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CropHistActionPerformed(evt);
            }
        });

        fruitSpot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unknown", "absent", "Colored", "Brown-w/blk-specks", "distort", "dna" }));
        fruitSpot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitSpotActionPerformed(evt);
            }
        });

        fruitingBodies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "absent", "present", "desconhecido" }));
        fruitingBodies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitingBodiesActionPerformed(evt);
            }
        });

        fruitingPods.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Norm", "Diseased", "few-present", "dna", " " }));
        fruitingPods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitingPodsActionPerformed(evt);
            }
        });

        germination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "90-100%", "80-89%", "lt-80%", "Desconhecido" }));
        germination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                germinationActionPerformed(evt);
            }
        });

        hail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no", "Desconhecido", " " }));
        hail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hailActionPerformed(evt);
            }
        });

        intDiscolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "None", "Brown", "Black", " " }));
        intDiscolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intDiscolorActionPerformed(evt);
            }
        });

        leafMalf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "absent", "Present", " " }));
        leafMalf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leafMalfActionPerformed(evt);
            }
        });

        leafMild.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "ausente", "Upper-surf", "Lower-surf" }));
        leafMild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leafMildActionPerformed(evt);
            }
        });

        leafspotMargin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "w-s-marg", "no-w-s-marg", "dna" }));
        leafspotMargin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leafspotMarginActionPerformed(evt);
            }
        });

        leaves.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Norm", "Abnorm" }));
        leaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leavesActionPerformed(evt);
            }
        });

        lodging.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Yes", "No" }));

        moldGrowth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Absent", "Present" }));
        moldGrowth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moldGrowthActionPerformed(evt);
            }
        });

        mycellium.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Absent", "Present" }));
        mycellium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycelliumActionPerformed(evt);
            }
        });

        plantStand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Normal", "lt-normal" }));
        plantStand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantStandActionPerformed(evt);
            }
        });

        root.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Norm", "Rotted", "galls-cysts" }));

        sclerotia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Absent", "Present" }));
        sclerotia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sclerotiaActionPerformed(evt);
            }
        });

        seeds.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Norm", "Abnorm" }));
        seeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedsActionPerformed(evt);
            }
        });

        seedDiscolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Absent", "Present" }));
        seedDiscolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedDiscolorActionPerformed(evt);
            }
        });

        stemCanker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Absent", "below-soil", "Above-soil", "Above-sec-nde" }));

        temps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "lt-norm", "norm", "gt-norm" }));
        temps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempsActionPerformed(evt);
            }
        });

        seedSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Norm", "lt-norm" }));
        seedSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedSizeActionPerformed(evt);
            }
        });

        leafShread.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "absent", "Present" }));
        leafShread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leafShreadActionPerformed(evt);
            }
        });

        shriveling.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Absent", "Present" }));
        shriveling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shrivelingActionPerformed(evt);
            }
        });

        leafspotSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "lt-1/8", "gt-1/8", "dna" }));
        leafspotSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leafspotSizeActionPerformed(evt);
            }
        });

        stem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Norm", "Abnorm" }));
        stem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stemActionPerformed(evt);
            }
        });

        seetTmt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "none", "fungicida", "Outros" }));
        seetTmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seetTmtActionPerformed(evt);
            }
        });

        precip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "lt-normal", "Normal", "gt-normal" }));
        precip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precipActionPerformed(evt);
            }
        });

        severity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Minor", "pot-severe", "severe" }));

        calcularSimilariedade.setText("Calcular Diagnóstico");
        calcularSimilariedade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularSimilariedade(evt);
            }
        });

        similaridadeMinima.setText("Similariedade minima para mostrar");
        similaridadeMinima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                similaridadeMinimaActionPerformed(evt);
            }
        });

        jLabel36.setText("Leafspot Halo");

        leafspotHalo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "absent", "yellow-halos", "no-yellow-halos", "Desconhecido", " " }));
        leafspotHalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leafspotHaloActionPerformed(evt);
            }
        });

        jLabel37.setText("plant Growth");

        plantGrowth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Norm", "Abnorm", " " }));
        plantGrowth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantGrowthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel35)
                                .addComponent(calcularSimilariedade, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(86, 86, 86)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(leafMalf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(intDiscolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(externalDecay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fruitSpot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fruitingBodies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fruitingPods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(germination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(leafMild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cankerLesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DamagedArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CropHist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(sclerotia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(plantStand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(mycellium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(leaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(86, 86, 86)
                                                .addComponent(leafspotMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel18)
                                                    .addComponent(jLabel17))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lodging, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(moldGrowth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel25)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(seedDiscolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel24)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(seeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(seedSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel32)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(stemCanker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel33)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(temps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(124, 124, 124)
                                        .addComponent(similaridadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(146, 146, 146)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(precip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel27)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(seetTmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(stem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                                .addComponent(leafspotSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel30)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(shriveling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(leafShread, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel28)
                                                    .addComponent(jLabel36)
                                                    .addComponent(jLabel37))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(severity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(leafspotHalo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(plantGrowth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                                .addGap(16, 16, 16))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jLabel34)))
                .addContainerGap(3693, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel35)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(DamagedArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cankerLesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CropHist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel17)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29)
                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(externalDecay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fruitSpot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(fruitingBodies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fruitingPods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(germination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)
                                    .addComponent(seeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37)
                                    .addComponent(plantGrowth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)
                                    .addComponent(seedDiscolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(intDiscolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32)
                                    .addComponent(stemCanker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel36)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(264, 264, 264)
                                            .addComponent(jLabel22))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel15)
                                                .addComponent(leafspotMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(leaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lodging, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(moldGrowth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(mycellium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(plantStand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(sclerotia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(leafMalf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel33)
                                .addComponent(temps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(leafShread, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(shriveling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(leafspotSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(stem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(seetTmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(precip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(severity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(leafspotHalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(similaridadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(leafMild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(seedSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcularSimilariedade, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(612, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DamagedAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DamagedAreaActionPerformed
        
    }//GEN-LAST:event_DamagedAreaActionPerformed
  
    private void leafspotMarginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leafspotMarginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leafspotMarginActionPerformed

    private void cankerLesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cankerLesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cankerLesionActionPerformed

    private void CropHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CropHistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CropHistActionPerformed

    private void fruitSpotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitSpotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fruitSpotActionPerformed

    private void germinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_germinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_germinationActionPerformed

    private void leafMalfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leafMalfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leafMalfActionPerformed

    private void leavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leavesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leavesActionPerformed


    private void CalcularSimilariedade(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularSimilariedade
        // TODO add your handling code here:
        DadosCasoProblema.leaves = getLeaves();
        DadosCasoProblema.data = getDate();
        DadosCasoProblema.plantstand=getPlantStand();
        DadosCasoProblema.precip=getPrecip();
        DadosCasoProblema.temp= getTemps();
        DadosCasoProblema.hail= getHail();
        DadosCasoProblema.seedtmt = getSeetTmt();
        DadosCasoProblema.plantgrowth= getPlantGrowth();
        DadosCasoProblema.leafspothalo= getLeafspotHalo();
        DadosCasoProblema.leafsspotmarg= getLeafspotMargin();
        DadosCasoProblema.leafspotsize= getLeafspotSize();
        DadosCasoProblema.leafshred= getLeafShread();
        DadosCasoProblema.leafmild = getLeafMild();
        DadosCasoProblema.stem = getStem();
        DadosCasoProblema.canckerlesion= getCankerLesion();
        DadosCasoProblema.fruitingbodies= getFruitingBodies();
        DadosCasoProblema.externaldecay = getExternalDecay();
        DadosCasoProblema.intdiscolor = getIntDiscolor();
        DadosCasoProblema.sclerotia= getSclerotia();
        DadosCasoProblema.fruitpods = getFruitingPods();
        DadosCasoProblema.fruitspots = getFruitingPods();
        DadosCasoProblema.seed= getSeeds();
        DadosCasoProblema.moldgrowth=getMoldGrowth();
        DadosCasoProblema.seeddis=getSeedDiscolor();
        DadosCasoProblema.shriveling= getShriveling();
        DadosCasoProblema.croohist=getCropHist();
        DadosCasoProblema.areadamaged=getDamagedArea();
        DadosCasoProblema.severity=getSeverity();
        DadosCasoProblema.germination=getGermination();
        DadosCasoProblema.lodgi = getLodging();
        DadosCasoProblema.stemcancker= getStemCanker();
        DadosCasoProblema.roots=getRoot();
        DadosCasoProblema.seedsize=getSeedSize();
        DadosCasoProblema.mycelium=getMycellium();
        DadosCasoProblema.leafmalf=getLeafMalf();
        RBCsoja rbc = new RBCsoja();
        rbc.calcSimiMain();
        Tela2 nomeVariavel = new Tela2(); 
        nomeVariavel.setVisible(true); 
        this.dispose();
        
    }//GEN-LAST:event_CalcularSimilariedade

    private void similaridadeMinimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_similaridadeMinimaActionPerformed
        // TODO add your handling code here:
        String porcentagem;
        porcentagem= similaridadeMinima.getText();
        DadosCasoProblema.calcMinima = Integer.valueOf(porcentagem);
        //System.out.println(DadosCasoProblema.calcMinima);
    }//GEN-LAST:event_similaridadeMinimaActionPerformed

    private void externalDecayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externalDecayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_externalDecayActionPerformed

    private void fruitingBodiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitingBodiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fruitingBodiesActionPerformed

    private void fruitingPodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitingPodsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fruitingPodsActionPerformed

    private void hailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hailActionPerformed

    private void plantStandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantStandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plantStandActionPerformed

    private void precipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precipActionPerformed

    private void tempsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempsActionPerformed

    private void seetTmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seetTmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seetTmtActionPerformed

    private void plantGrowthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantGrowthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plantGrowthActionPerformed

    private void leafspotHaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leafspotHaloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leafspotHaloActionPerformed

    private void leafspotSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leafspotSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leafspotSizeActionPerformed

    private void leafShreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leafShreadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leafShreadActionPerformed

    private void leafMildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leafMildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leafMildActionPerformed

    private void stemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stemActionPerformed

    private void intDiscolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intDiscolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intDiscolorActionPerformed

    private void sclerotiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sclerotiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sclerotiaActionPerformed

    private void seedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seedsActionPerformed

    private void moldGrowthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moldGrowthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moldGrowthActionPerformed

    private void seedDiscolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedDiscolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seedDiscolorActionPerformed

    private void seedSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seedSizeActionPerformed

    private void shrivelingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shrivelingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shrivelingActionPerformed

    private void mycelliumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycelliumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mycelliumActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    public String getMycellium() {
        String casoProblema;
        Object objeto= mycellium.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setMycellium(JComboBox<String> mycellium) {
        this.mycellium = mycellium;
    }

    public String getShriveling() {
        String casoProblema;
        Object objeto= shriveling.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setShriveling(JComboBox<String> shriveling) {
        this.shriveling = shriveling;
    }

    public String getSeedSize() {
        String casoProblema;
        Object objeto= seedSize.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setSeedSize(JComboBox<String> seedSize) {
        this.seedSize = seedSize;
    }

    public String getSeedDiscolor() {
        String casoProblema;
        Object objeto= seedDiscolor.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setSeedDiscolor(JComboBox<String> seedDiscolor) {
        this.seedDiscolor = seedDiscolor;
    }

    public String getMoldGrowth() {
        String casoProblema;
        Object objeto= moldGrowth.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setMoldGrowth(JComboBox<String> moldGrowth) {
        this.moldGrowth = moldGrowth;
    }

    public String getSeeds() {
        String casoProblema;
        Object objeto= seeds.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setSeeds(JComboBox<String> seeds) {
        this.seeds = seeds;
    }

    public String getSclerotia() {
        String casoProblema;
        Object objeto= sclerotia.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setSclerotia(JComboBox<String> sclerotia) {
        this.sclerotia = sclerotia;
    }

    public String getIntDiscolor() {
        String casoProblema;
        Object objeto= intDiscolor.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setIntDiscolor(JComboBox<String> intDiscolor) {
        this.intDiscolor = intDiscolor;
    }

    public String getStem() {
        String casoProblema;
        Object objeto= stem.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setStem(JComboBox<String> stem) {
        this.stem = stem;
    }

    public String getLeafMild() {
        String casoProblema;
        Object objeto= leafMild.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setLeafMild(JComboBox<String> leafMild) {
        this.leafMild = leafMild;
    }

    public String getLeafShread() {
        String casoProblema;
        Object objeto= leafspotHalo.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setLeafShread(JComboBox<String> leafShread) {
        this.leafShread = leafShread;
    }

    public String getLeafspotSize() {
        String casoProblema;
        Object objeto= leafspotSize.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setLeafspotSize(JComboBox<String> leafspotSize) {
        this.leafspotSize = leafspotSize;
    }

    public String getLeafspotHalo() {
        String casoProblema;
        Object objeto= leafspotHalo.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setLeafspotHalo(JComboBox<String> leafspotHalo) {
        this.leafspotHalo = leafspotHalo;
    }

    public String getPlantGrowth() {
        String casoProblema;
        Object objeto= plantGrowth.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setPlantGrowth(JComboBox<String> plantGrowth) {
        this.plantGrowth = plantGrowth;
    }

    public String getSeetTmt() {
        String casoProblema;
        Object objeto= seetTmt.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setSeetTmt(JComboBox<String> seetTmt) {
        this.seetTmt = seetTmt;
    }

    public String getTemps() {
        String casoProblema;
        Object objeto= temps.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setTemps(JComboBox<String> temps) {
        this.temps = temps;
    }

    public String getPrecip() {
        String casoProblema;
        Object objeto= precip.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setPrecip(JComboBox<String> precip) {
        this.precip = precip;
    }

    public String getPlantStand() {
        String casoProblema;
        Object objeto= plantStand.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setPlantStand(JComboBox<String> plantStand) {
        this.plantStand = plantStand;
    }

    public String getHail() {
        String casoProblema;
        Object objeto= hail.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setHail(JComboBox<String> hail) {
        this.hail = hail;
    }

    public String getFruitingPods() {
        String casoProblema;
        Object objeto= fruitingPods.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setFruitingPods(JComboBox<String> fruitingPods) {
        this.fruitingPods = fruitingPods;
    }

    public String getFruitingBodies() {
        String casoProblema;
        Object objeto= fruitingBodies.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setFruitingBodies(JComboBox<String> fruitingBodies) {
        this.fruitingBodies = fruitingBodies;
    }

    public String getExternalDecay() {
        String casoProblema;
        Object objeto= externalDecay.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setExternalDecay(JComboBox<String> externalDecay) {
        this.externalDecay = externalDecay;
    }
    
    public String getLeaves() {
        String casoProblema;
        Object objeto= leafspotHalo.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setLeaves(JComboBox<String> leaves) {
        this.leaves = leaves;
    }
    
     public String getCropHist() {
        String casoProblema;
        Object objeto= CropHist.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setCropHist(JComboBox<String> CropHist) {
        this.CropHist = CropHist;
    }

    public String getDate() {
        String casoProblemaData;
        Object objeto= date.getSelectedItem();
        casoProblemaData = objeto.toString();
        return casoProblemaData;
    }

    public void setDate(JComboBox<String> date) {
        this.date = date;
    }

    public String getGermination() {
        String casoProblema;
        Object objeto= germination.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setGermination(JComboBox<String> germination) {
        this.germination = germination;
    }

    public String getLeafMalf() {
        String casoProblema;
        Object objeto= leafMalf.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setLeafMalf(JComboBox<String> leafMalf) {
        this.leafMalf = leafMalf;
    }

    public String getLodging() {
        String casoProblema;
        Object objeto= lodging.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setLodging(JComboBox<String> lodging) {
        this.lodging = lodging;
    }

    public String getRoot() {
        String casoProblema;
        Object objeto= root.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setRoot(JComboBox<String> root) {
        this.root = root;
    }

    public String getSeverity() {
        String casoProblema;
        Object objeto= severity.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setSeverity(JComboBox<String> severity) {
        this.severity = severity;
    }

    public String getStemCanker() {
        String casoProblema;
        Object objeto= stemCanker.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setStemCanker(JComboBox<String> stemCanker) {
        this.stemCanker = stemCanker;
    }
    
    public String getFruitSpot() {
         String casoProblema;
        Object objeto= fruitSpot.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setFruitSpot(JComboBox<String> fruitSpot) {
        this.fruitSpot = fruitSpot;
    }
    

    public String getDamagedArea() {
        String casoProblema;
        Object objeto= DamagedArea.getSelectedItem();
        casoProblema = objeto.toString();
        //System.out.println(casoProblema);
        return casoProblema;
    }

    public void setDamagedArea(JComboBox<String> DamagedArea) {
        this.DamagedArea = DamagedArea;
    }
    public String getCankerLesion() {
        String casoProblema;
        Object objeto= cankerLesion.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setCankerLesion(JComboBox<String> cankerLesion) {
        this.cankerLesion = cankerLesion;
    }

    public String getLeafspotMargin() {
        String casoProblema;
        Object objeto= leafspotMargin.getSelectedItem();
        casoProblema = objeto.toString();
        return casoProblema;
    }

    public void setLeafspotMargin(JComboBox<String> leafspotMargin) {
        this.leafspotMargin = leafspotMargin;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CropHist;
    public javax.swing.JComboBox<String> DamagedArea;
    private javax.swing.JButton calcularSimilariedade;
    private javax.swing.JComboBox<String> cankerLesion;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JComboBox<String> externalDecay;
    private javax.swing.JComboBox<String> fruitSpot;
    private javax.swing.JComboBox<String> fruitingBodies;
    private javax.swing.JComboBox<String> fruitingPods;
    private javax.swing.JComboBox<String> germination;
    private javax.swing.JComboBox<String> hail;
    private javax.swing.JComboBox<String> intDiscolor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> leafMalf;
    private javax.swing.JComboBox<String> leafMild;
    private javax.swing.JComboBox<String> leafShread;
    private javax.swing.JComboBox<String> leafspotHalo;
    private javax.swing.JComboBox<String> leafspotMargin;
    private javax.swing.JComboBox<String> leafspotSize;
    private javax.swing.JComboBox<String> leaves;
    private javax.swing.JComboBox<String> lodging;
    private javax.swing.JComboBox<String> moldGrowth;
    private javax.swing.JComboBox<String> mycellium;
    private javax.swing.JComboBox<String> plantGrowth;
    private javax.swing.JComboBox<String> plantStand;
    private javax.swing.JComboBox<String> precip;
    private javax.swing.JComboBox<String> root;
    private javax.swing.JComboBox<String> sclerotia;
    private javax.swing.JComboBox<String> seedDiscolor;
    private javax.swing.JComboBox<String> seedSize;
    private javax.swing.JComboBox<String> seeds;
    private javax.swing.JComboBox<String> seetTmt;
    private javax.swing.JComboBox<String> severity;
    private javax.swing.JComboBox<String> shriveling;
    private javax.swing.JTextField similaridadeMinima;
    private javax.swing.JComboBox<String> stem;
    private javax.swing.JComboBox<String> stemCanker;
    private javax.swing.JComboBox<String> temps;
    // End of variables declaration//GEN-END:variables
}
